feat(makepkg-bwrap): support rust

diff --git a/bin/makepkg-bwrap b/bin/makepkg-bwrap
--- a/bin/makepkg-bwrap
+++ b/bin/makepkg-bwrap
@@ -1,6 +1,12 @@
 #!/bin/bash
 
 mkdir -m 700 -p ~/.makepkg/gnupg
+TEMPDIR="$(mktemp -d -p /tmp makepkg.XXXXXXXXXX)"
+if [[ $? -ne 0 ]]; then
+    echo "\033[31mFail to make temp directory!\033[0m"
+    exit 1
+fi
+
 bwrap \
     --unshare-all --share-net --die-with-parent \
     --ro-bind /usr /usr --ro-bind /opt /opt --ro-bind /etc /etc \
@@ -10,9 +16,13 @@ bwrap \
     --symlink usr/lib /lib \
     --symlink usr/lib /lib64 \
     --ro-bind /var/lib/pacman /var/lib/pacman \
-    --ro-bind ~/.ccache ~/.ccache \
+    --bind $TEMPDIR ~ \
     --bind ~/.cache ~/.cache \
     --bind ~/.makepkg/gnupg ~/.gnupg \
+    --ro-bind ~/.ccache ~/.ccache \
+    --ro-bind ~/.rustup ~/.rustup \
     --setenv FAKEROOTDONTTRYCHOWN 1 \
     --bind $PWD $PWD \
     /usr/bin/makepkg "$@"
+
+rm -rf "$TEMPDIR"
